name: visualingo_venv
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - aom=3.6.1
  - astunparse=1.6.3
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - cpuonly=2.0
  - datasets=3.5.0
  - dill=0.3.8
  - expat=2.7.0
  - ffmpeg=4.4.2
  - filelock=3.18.0
  - flatbuffers=24.12.23
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gast=0.6.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - google-pasta=0.2.0
  - grpcio=1.67.1
  - h2=4.2.0
  - h5py=3.13.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - huggingface_hub=0.30.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - intel-openmp=2022.0.1
  - jinja2=3.1.6
  - keras=3.9.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.67.1
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - mkl=2022.1.0
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.4.3
  - multiprocess=0.70.16
  - namex=0.0.9
  - ncurses=6.4
  - nettle=3.9.1
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numpy=2.2.5
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - optree=0.15.0
  - orc=2.1.1
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.1
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - protobuf=5.28.3
  - pthread-stubs=0.4
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=14.0.0
  - s2n=1.5.14
  - safetensors=0.5.3
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.32.3
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.1
  - transformers=4.51.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.4.0
  - wayland=1.23.1
  - wayland-protocols=1.43
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - click==8.1.8
      - fastapi==0.115.12
      - ffmpy==0.5.0
      - gradio==5.29.0
      - gradio-client==1.10.0
      - groovy==0.1.2
      - gtts==2.5.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - orjson==3.10.18
      - pickle-mixin==1.0.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - python-multipart==0.0.20
      - ruff==0.11.8
      - safehttpx==0.1.6
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.46.2
      - tomlkit==0.13.2
      - typer==0.15.3
      - typing-inspection==0.4.0
      - uvicorn==0.34.2
      - websockets==15.0.1
